[package]
name = "syncer-extension-json"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
description = "Official json extension for syncer"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
syncer-language.workspace = true
syncer-extension-sdk.workspace = true
